name: Manual Release

on:
  workflow_dispatch: 

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: v0.1.0  
        release_name: 'Release v0.1.0'
        body: 'Latest release'
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload JAR to GitHub Release
      uses: actions/upload-release-asset@v1
      with:
        url: ${{ steps.create_release.outputs.upload_url }}  
        asset_path: target/emailapi-0.0.1-SNAPSHOT.jar 
        asset_name: emailapi-0.0.1-SNAPSHOT.jar
        asset_content_type: application/java-archive
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
